apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stroinadzor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
    - api.stroinadzor.ru
    secretName: stroinadzor-tls
  rules:
  - host: api.stroinadzor.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stroinadzor-api
            port:
              number: 80
